# frozen_string_literal: true

require_relative 'alert_arbitrary_period_configurable_comparison_mixin'

class AlertConfigurablePeriodGasComparison < AlertArbitraryPeriodComparisonGasBase
  include AlertArbitraryPeriodConfigurableComparisonMixIn
end
