# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "bundler" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "tuesday"
    ignore:
      # seems like once dependabot has opened a PR for a new minor version it won't do others even if they're security
      # updates - so ignore new minor versions (they need manual intervention anyway)
      - dependency-name: "rails"
        update-types: ["version-update:semver-minor"]
    open-pull-requests-limit: 10 # default 5
