inputs:
  ruby-only:
    type: boolean
    description: only setup ruby
    default: false
runs:
  using: composite
  steps:
    - if: ${{ ! inputs.ruby-only }}
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: yarn
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: "3.0"
    - if: ${{ ! inputs.ruby-only }}
      run: bundle exec rails db:schema:load
      shell: bash
    - if: ${{ ! inputs.ruby-only }}
      run: bundle exec rake assets:precompile
      shell: bash
