inputs:
  ruby-only:
    type: boolean
    description: only setup ruby
    default: false
runs:
  steps:
    - uses: actions/setup-node@v3
      if: ${{ ! inputs.ruby-only }}
      with:
        node-version: 16
        cache: yarn
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: "3.0"
    - run: bin/rails db:schema:load
      if: ${{ ! inputs.ruby-only }}
    - run: bundle exec rake assets:precompile
      if: ${{ ! inputs.ruby-only }}
