# using https://github.com/microsoft/action-python/blob/main/action.yml as an example
name: 'Rails Test Setup'
inputs:
  ruby-only:
    description: only setup ruby
    default: false
runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: "3.2"
    - if: ${{ inputs.ruby-only == 'false' }}
      run: bundle exec rails db:schema:load
      shell: bash
    - if: ${{ inputs.ruby-only == 'false' }}
      run: bundle exec rake assets:precompile
      shell: bash
    - if: ${{ inputs.ruby-only == 'false' }}
      run: sudo apt update && sudo apt install -y imagemagick
      shell: bash
