# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  rspec_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.2']
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec overcommit --sign && bundle exec overcommit --run
      env:
        GIT_AUTHOR_NAME: Over Commit
        GIT_AUTHOR_EMAIL: overcommit@localhost
        SKIP: ForbiddenBranches # this fails when triggered by master push
    - run: bundle exec rspec

  analytics_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.2']
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run standard test
      run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/standard_test_github_actions.rb

    # - name: Run standard tests
    #   run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/standard_test.rb

    # - name: Run adult dashboard tests
    #   run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/test_adult_dashboard.rb

    # - name: Run alert tests
    #   run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/test_alerts.rb

    # - name: Run alert heating off forcast scenarios tests
    #   run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/test_alerts_heating_off_forecast_scenarios.rb

    # - name: Run all test
    #   run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/test_all

    # - name: Run all short test
    #   run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/test_all_short.rb

    # - name: Run benchmarks tests
    #   run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/test_benchmarks.rb

    # - name: Run charts tests
    #   run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/test_charts.rb

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: analytics-test-artifacts-${{ matrix.ruby-version }}
        path: |
          test_output
          !./test_output/MeterCollections
        retention-days: 7
