---
EnableDefaultLinters: true
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      require:
        - rubocop-rails
      Layout/InitialIndentation:
        Enabled: false # erb-lint recommended
      Layout/TrailingEmptyLines:
        Enabled: false # erb-lint recommended
      Naming/AsciiIdentifiers:
        Enabled: false # because of £ usage
      Style/FrozenStringLiteralComment:
        Enabled: false # erb-lint recommended
      Lint/UselessAssignment:
        Enabled: false # erb-lint recommended
      Rails/OutputSafety:
        Enabled: false # erb-lint recommended
      Style/HashSyntax:
        EnforcedShorthandSyntax: never # get ActionView::SyntaxErrorInTemplate without this
