inherit_from: <%= ENV.key?('CI') ? '.rubocop_todo.yml' : '/dev/null' %>

inherit_mode:
  merge:
    - Exclude
    - Include

AllCops:
  NewCops: enable
  Exclude:
    # exclude as these files are updated/managed by rails app:upgrade
    - bin/rails
    - bin/rake
    - bin/setup
    - bin/yarn
    - config/application.rb
    - config/boot.rb
    - config/environment.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - config/environments/test.rb
    - config/initializers/assets.rb
    - config/initializers/backtrace_silencers.rb
    - config/initializers/content_security_policy.rb
    - config/initializers/filter_parameter_logging.rb
    - config/initializers/new_framework_defaults_6_1.rb
    - config/initializers/permissions_policy.rb
    - config/puma.rb
    - config/routes.rb
plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

Metrics/MethodLength:
  Max: 30 # default 10

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - and
RSpec/ExampleLength:
  Max: 15 # default 5
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Max: 10 # default 5
RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false
