# inherit_from: .rubocop_todo.yml

## regenerate .rubocop_todo.yml after any changes to this config using:
## rubocop --auto-gen-config --exclude-limit=1000
AllCops:
  NewCops: enable
  # SuggestExtensions: false
require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - and
RSpec/ExampleLength:
  Enabled: false
RSpec/Focus:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
