inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
#  Include:
#    - 'app/**/*.rb'
#    - 'lib/**/*.rb'
#  Disable specs for now
#   - 'spec/**/*.rb'
#  Exclude:
#    - 'app/services/schools/funding_status_lookup.rb'
#    - 'lib/data_feeds/weather_underground_loader.rb'
#    - 'lib/data_feeds/solar_pv_tuos_loader.rb'
#    - 'lib/data_feeds/dark_sky_temperature_loader.rb'
#    - 'lib/data_feeds/solar_pv_tuos_v2_loader.rb'
#    - 'bin/**'
#    - 'script/**'
#    - 'node_modules/**'
#    - 'node_modules/node-sass/src/libsass/script/spec'

require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

# Should inheret the defaults: https://github.com/rubocop/rubocop/blob/master/config/default.yml
# Override our specific requirements here
Style/KeywordParametersOrder:
  AutoCorrect: false
Bundler/OrderedGems:
  Enabled: false
RSpec/VariableName:
  AllowedPatterns:
    - _£_