inherit_from: <%= ENV.key?('CI') ? '.rubocop_todo.yml' : '/dev/null' %>

inherit_mode:
  merge:
    - Exclude
    - Include

AllCops:
  NewCops: enable
  Exclude:
    # exclude as these files are updated/managed by rails app:upgrade
    - bin/rails
    - bin/rake
    - bin/setup
    - bin/yarn
    - config/application.rb
    - config/boot.rb
    - config/environment.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - config/environments/test.rb
    - config/initializers/assets.rb
    - config/initializers/backtrace_silencers.rb
    - config/initializers/content_security_policy.rb
    - config/initializers/filter_parameter_logging.rb
    - config/initializers/new_framework_defaults_6_1.rb
    - config/initializers/permissions_policy.rb
    - config/puma.rb
    - config/routes.rb
plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

Metrics/MethodLength:
  Max: 30 # default 10

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - and
RSpec/ExampleLength:
  Max: 15 # default 5
RSpec/MultipleExpectations:
  Max: 5 # default 1
RSpec/MultipleMemoizedHelpers:
  Max: 10 # default 5
RSpec/NestedGroups:
  Max: 4 # default 3

# For discussion. Alternatives are enable_bootstrap5 or enable_bootstrap_five
# enable_bootstrap_5 is going to be used in lots of controllers, don't want to having to keep switching it off inline
# everytime it's used, so have put it here.
Naming/VariableNumber:
  EnforcedStyle: normalcase
  AllowedIdentifiers:
    - enable_bootstrap_5

Style/Documentation:
  Enabled: false
