# regenerate .rubocop_todo.yml after any changes to this config using:
# rubocop --regenerate-todo
inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - "data/**/*"
    # exclude as these files are updated/managed by rails app:upgrade
    - bin/rails
    - bin/rake
    - bin/setup
    - bin/yarn
    - config/application.rb
    - config/boot.rb
    - config/environment.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - config/environments/test.rb
    - config/initializers/assets.rb
    - config/initializers/backtrace_silencers.rb
    - config/initializers/content_security_policy.rb
    - config/initializers/filter_parameter_logging.rb
    - config/initializers/new_framework_defaults_6_1.rb
    - config/initializers/permissions_policy.rb
    - config/puma.rb
    - config/routes.rb
require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - and
RSpec/ExampleLength:
  Enabled: false
RSpec/Focus:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false
