# frozen_string_literal: true

namespace :scss do
  task :colours, [:mode] => :environment do |_, args|
    args.with_defaults(mode: :generate)
    template_path = 'app/assets/stylesheets/_colours.scss.erb'
    output = ERB.new(File.read(template_path)).result(binding)
    output = "// DO NOT MODIFY\n" \
             "// this file is generated by bin/rake scss:colours\n" \
             "// modify #{template_path} or config/initializers/colours.rb instead\n\n#{output}"
    file_check_write(args, output, template_path.delete_suffix('.erb'))
  end
end
