# frozen_string_literal: true

namespace :scss do
  task :colours, [:mode] => :environment do |_, args|
    args.with_defaults(mode: :generate)
    template_path = 'app/assets/stylesheets/_colours.scss.erb'
    output_path = template_path.delete_suffix('.erb')
    output = ERB.new(File.read(template_path)).result(binding)
    output = "// DO NOT MODIFY\n" \
             "// this file is generated by bin/rake scss:colours\n" \
             "// modify #{template_path} instead\n\n#{output}"
    if args[:mode] == 'check'
      exit File.read(output_path) == output ? 0 : 1
    else
      File.write(output_path, output)
      puts "Generated #{output_path}"
    end
  end
end
