# frozen_string_literal: true

def file_check_write(args, output, output_path)
  args.with_defaults(mode: :generate)
  if args[:mode] == 'check'
    exit File.read(output_path) == output ? 0 : 1
  else
    File.write(output_path, output)
    puts "Generated #{output_path}"
  end
end

namespace :scss do
  task :components, [:mode] => :environment do |_, args|
    Dir.chdir('app/components')
    imports = Dir.glob('*/**/*.scss').map do |filename|
      "@import \"#{filename.delete_suffix('.scss')}\";\n"
    end
    file_check_write(args,
                     "// DO NOT MODIFY\n// this file is generated by bin/rake scss:components\n\n#{imports.join}",
                     '_index.scss')
  end
end
