# For full config options, check the docs:
#    docs.serverless.com

service: analytics-pipeline
frameworkVersion: '3'
useDotenv: true
configValidationMode: error

plugins:
  - serverless-ruby-layer

custom:
  rubyLayer:
    use_docker: true
    docker_file: Dockerfile
    native_libs:
      - /lib64/libpq.so.5
      - /lib64/libldap_r-2.4.so.2
      - /lib64/liblber-2.4.so.2
      - /lib64/libsasl2.so.3
      - /lib64/libssl3.so
      - /lib64/libsmime3.so
      - /lib64/libnss3.so
      - /lib64/libnssutil3.so

provider:
  name: aws
  runtime: ruby3.2
  # architecture: arm64
  region: eu-west-2
  stage: ${opt:stage, 'development'}
  environment:
    IN_BUCKET: es-${self:provider.stage}-analytics-in
    OUT_BUCKET: es-${self:provider.stage}-analytics-out
    ROLLBAR_ACCESS_TOKEN: ${env:ROLLBAR_ACCESS_TOKEN}
    DEV_DB_HOST: ${env:DEV_DB_HOSTNAME}
    DEV_DB_USERNAME: ${env:DEV_DB_USERNAME}
    DEV_DB_PASSWORD: ${env:DEV_DB_PASSWORD}
    # this allows bundler to pick up git gems in /opt/ruby/3.2.0/bundler from the ruby layer
    BUNDLE_PATH: /opt
    BUNDLE_WITHOUT: test:development
    LD_LIBRARY_PATH: /var/lang/lib:/var/lang/lib:/opt/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib
                     /var/lang/lib:/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ]]}
            - "arn:aws:s3:::${self:provider.environment.IN_BUCKET}/*"
            - "arn:aws:s3:::${self:provider.environment.OUT_BUCKET}/*"

package:
  patterns:
    - '!**'
    - 'handler.rb'
    - '../lib/**'
    - '../app/**'
    - '../config/**'
    - 'Gemfile'
    - '../Gemfile.lock'

functions:
  process:
    handler: handler.run
    events:
      - s3: ${self:provider.environment.IN_BUCKET}
    reservedConcurrency: 2
    vpc:
      securityGroupIds:
        - sg-9474a8ff
      subnetIds:
        - subnet-851614c8
        - subnet-c12f90a8
        - subnet-13a15d69

resources:
  Resources:
    S3BucketOut:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.OUT_BUCKET}
