service: analytics-pipeline
frameworkVersion: '3'
useDotenv: true
configValidationMode: error

provider:
  name: aws
  # runtime: ruby3.2
  # architecture: arm64
  region: eu-west-2
  stage: ${opt:stage, 'development'}
  environment:
    ROLLBAR_ACCESS_TOKEN: ${env:ROLLBAR_ACCESS_TOKEN}
    RDS_DB_NAME: ${env:RDS_DB_NAME}
    RDS_HOSTNAME: ${env:RDS_HOSTNAME}
    RDS_PASSWORD: ${env:RDS_PASSWORD}
    RDS_PORT: ${env:RDS_PORT}
    RDS_USERNAME: ${env:RDS_USERNAME}
    SECRET_KEY_BASE: ${env:SECRET_KEY_BASE}
    ENCRYPTED_FIELD_SALT: ${env:ENCRYPTED_FIELD_SALT}
    RAILS_ENV: production
    AWS_S3_ACTIVE_STORAGE_BUCKET: dontuse
    RAILS_LOG_TO_STDOUT: 1
    QUEUE_URL: ${construct:my-queue.queueUrl}
  ecr:
   images:
    appimage:
      path: ..
      file: serverless/Dockerfile

plugins:
  - serverless-lift

constructs:
  my-queue:
    type: queue
    maxRetries: 1
    maxConcurrency: 50
    extensions:
      queue:
        Properties:
          VisibilityTimeout: 120 # by default this is * 6 the timeout which seems too high since we don't retry
    worker:
      image:
        name: appimage
        command:
          - handler.run
      timeout: 120
      vpc:
        securityGroupIds:
          - sg-9474a8ff
        subnetIds:
          - subnet-851614c8
          - subnet-c12f90a8
          - subnet-13a15d69
