schools:
  - name: 'cefn-hengoed-community-school'
    description: 'multiple solar production meters'
  - name: 'green-lane-ce-primary'
    description: 'vanilla primary with electric and gas meters'
  - name: 'hugh-sexey-c-of-e-middle-school'
    description: 'sheffield simulated solar PV school'
  - name: 'king-james-1-community-academy'
    description: 'vanilla secondary with electric and gas meters'
  - name: 'long-furlong-primary-school'
    description: 'vanilla rbee-lch solar PV school'
  - name: 'marksbury-c-of-e-primary-school'
    description: 'vanilla storage heater school'
  - name: 'newcastle-high-school-for-girls-senior-school'
    description: 'school with many meters'
  - name: 'pennyland-primary-school'
    description: 'school with multiple storage heater meters'
  - name: 'ph-school'
    description: 'DCC school with differential tariffs'
